# numpy

In [3]:
import numpy as np

In [2]:
myarr=np.array([[1,2,34,5]],np.int8)

In [3]:
myarr[0]

array([ 1,  2, 34,  5], dtype=int8)

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int8')

In [13]:
listarray=np.array([[1,2,3],[1,3,4],[2,6,7]],np.int32)

In [14]:
print(listarray)

[[1 2 3]
 [1 3 4]
 [2 6 7]]


In [11]:
listarray

array([[1, 2, 3],
       [1, 3, 4],
       [2, 6, 7]])

In [15]:
listarray.dtype

dtype('int32')

In [16]:
listarray.shape

(3, 3)

In [18]:
np.array({32,34,26})

array({32, 34, 26}, dtype=object)

In [19]:
np.array({'32':653287,'y':34,'h':26})

array({'32': 653287, 'y': 34, 'h': 26}, dtype=object)

In [25]:
lspace = np.linspace(1,10,5)

In [26]:
lspace

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [23]:
emp = np.empty((4,5))

In [24]:
emp

array([[ 1.64003851e-316,  0.00000000e+000,  6.91953394e-310,
        -1.03999579e+001,  6.91953659e-310],
       [ 6.91953403e-310,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000]])

In [27]:
emp_like=np.empty_like(lspace)

In [28]:
emp_like

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [33]:
id = np.identity(15) #creates a identity matrix

In [34]:
id

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [38]:
ar=np.arange(36)

In [39]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [40]:
print(ar)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]


In [41]:
ar.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [42]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [43]:
ar=ar.reshape(6,6)

In [44]:
ar

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [47]:
ar=ar.ravel()

In [48]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [49]:
ar.shape

(36,)

In [51]:
k=np.array([[[2,3]]])

In [52]:
print(k)

[[[2 3]]]


In [53]:
k[0,0,0]

2

In [55]:
k[0,0,1]

3

In [56]:
k.shape

(1, 1, 2)

In [30]:
x=[[1,2,3],[4,115,64],[7,8,9]]

In [31]:
arr = np.array(x)

In [5]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arr.sum(axis=0)

array([12, 15, 18])

In [8]:
arr.sum(axis=1)

array([ 6, 15, 24])

In [10]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [12]:
arr.flat

In [23]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [17]:
arr.ndim

2

In [19]:
arr.size

9

In [24]:
arr.nbytes

72

In [7]:
one= np.array([13,44,56,7869,8])

In [8]:
one.argmax()

3

In [9]:
one.argmin()

4

In [10]:
one.argsort()

array([4, 0, 1, 2, 3])

In [24]:
arr

array([[ 1,  2,  3],
       [ 4,  5, 64],
       [ 7,  8,  9]])

In [18]:
arr.argmax()

8

In [25]:
arr.sort()

In [26]:
arr

array([[ 1,  2,  3],
       [ 4,  5, 64],
       [ 7,  8,  9]])

In [27]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [28]:
arr.argmax()

5

In [32]:
arr.argmax(axis=1)

array([2, 1, 2])

In [34]:
l=[[1,2,3],[4,5,6],[7,8,9]]

In [35]:
arr2=np.array(l)

In [36]:
arr+l

array([[  2,   4,   6],
       [  8, 120,  70],
       [ 14,  16,  18]])

In [37]:
arr*l

array([[  1,   4,   9],
       [ 16, 575, 384],
       [ 49,  64,  81]])

In [38]:
arr-l


array([[  0,   0,   0],
       [  0, 110,  58],
       [  0,   0,   0]])

In [39]:
o=arr-l

In [40]:
o

array([[  0,   0,   0],
       [  0, 110,  58],
       [  0,   0,   0]])

In [41]:
np.sqrt(o)

array([[ 0.        ,  0.        ,  0.        ],
       [ 0.        , 10.48808848,  7.61577311],
       [ 0.        ,  0.        ,  0.        ]])

In [43]:
np.where(arr>5)

(array([1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2]))

In [44]:
arr

array([[  1,   2,   3],
       [  4, 115,  64],
       [  7,   8,   9]])

In [1]:
import sys

In [2]:
py_ar=[0,4,55,2]

In [4]:
np_ar=np.array(py_ar)

In [5]:
sys.getsizeof(1)

28

In [6]:
sys.getsizeof(1)*len(py_ar)

112

In [7]:
np_ar.itemsize

8

In [8]:
np_ar.itemsize * np_ar.size

32

In [10]:
np_ar.tolist()

[0, 4, 55, 2]